### PR TITLE
added onnxruntime and upgrade ultralytics

### PR DESCRIPTION
**Pull request by mchtey**

### CODE REVIEW

**Comment by isms** [comment]
@mchtey Thanks for the PR. One question - is it possible to add the package you want without changing the ultralytics package? We would like to keep the environment stable to avoid impacting others who may be using ultralytics.

I see the versions suggest this is just a patch update (8.1.11 to 8.1.27), so alternatively if you can look at the changelog for ultralytics and flag anything that may be problematic or explain why nothing should impact others we can consider it.

**Comment by isms** [comment]
@mchtey The build has failed with the proposed change though, see here: https://github.com/drivendataorg/spacecraft-pose-object-detection-runtime/actions/runs/8310616225/job/22760366309?pr=15#step:4:803

Please make sure you're able to build this locally (`make build`) before requesting re-review.

**Comment by isms** [comment]
@mchtey Are you still interested in getting this PR merged? Let us know if you want to keep it open.

**Comment by mchtey** [comment]
image

Hi,
It seems that there is an issue related to the ncnn library here. However, there is no such change in the pull request (PR) I have submitted. Could you please double-check? I acknowledge that I'm a novice, but the issue might not be in my PR. It appears that the ncnn extension has been added in a PR submitted after mine.
Thank you.

**Comment by isms** [comment]
@mchtey That version is not available yet: https://anaconda.org/conda-forge/ultralytics/labels

**Comment by mchtey** [comment]
I asked the developers and this is what they told me.  _**"Oh yea looks like updates haven't gotten pushed there in a while. I'll look into this quick but might need to raise this with someone else on the Team."**_

**Comment by mananjhaveri** [comment]
Hello @mchtey @isms 
What's the latest with this PR? 

I would also want a version bump for the `ultralytics` package so that I can experiment with `yolov9`. I would also like to experiment with `onnx`, so it would be helpful if we can add the `onnxruntime` package as well.

If there is a concern regarding `ultralytics` version bump, can we at least take forward this PR with just the addition of `onnxruntime`?

**Comment by isms** [comment]
@mchtey Thanks for the update - just ran the build and it looks like we're good to go. Merging!

**Comment by mchtey** [comment]
@isms thank you very much :)

**Pull request merged**
